package xyz.ggeorge.theme

import androidx.compose.ui.graphics.Color

// FISE SMS Response State | Light Theme
val FiseSuccessfullColorLight = Color(0xFF8BF89E)
val FiseWrongColorLight = Color(0xFFE2DBB9)
val FiseWasProcessedColorLight = Color(0xFFF1CCC4)

// FISE SMS Response State | Dark Theme
val FiseSuccessfullColorDark = Color(0xFF14352b)
val FiseWrongColorDark = Color(0xFF49473a)
val FiseWasProcessedColorDark = Color(0xFF5f3f37)

val md_theme_light_primary = Color(0xFF006E11)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF86FC7B)
val md_theme_light_onPrimaryContainer = Color(0xFF002202)
val md_theme_light_secondary = Color(0xFF53634E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD6E8CE)
val md_theme_light_onSecondaryContainer = Color(0xFF111F0F)
val md_theme_light_tertiary = Color(0xFF006685)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBEE9FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F2A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFDF6)
val md_theme_light_onBackground = Color(0xFF1A1C19)
val md_theme_light_surface = Color(0xFFFCFDF6)
val md_theme_light_onSurface = Color(0xFF1A1C19)
val md_theme_light_surfaceVariant = Color(0xFFDEE4D8)
val md_theme_light_onSurfaceVariant = Color(0xFF42493F)
val md_theme_light_outline = Color(0xFF73796E)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1EB)
val md_theme_light_inverseSurface = Color(0xFF2F312D)
val md_theme_light_inversePrimary = Color(0xFF6ADF62)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006E11)
val md_theme_light_outlineVariant = Color(0xFFC2C8BC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF6ADF62)
val md_theme_dark_onPrimary = Color(0xFF003A05)
val md_theme_dark_primaryContainer = Color(0xFF00530A)
val md_theme_dark_onPrimaryContainer = Color(0xFF86FC7B)
val md_theme_dark_secondary = Color(0xFFBACCB2)
val md_theme_dark_onSecondary = Color(0xFF263422)
val md_theme_dark_secondaryContainer = Color(0xFF3C4B38)
val md_theme_dark_onSecondaryContainer = Color(0xFFD6E8CE)
val md_theme_dark_tertiary = Color(0xFF6AD3FF)
val md_theme_dark_onTertiary = Color(0xFF003546)
val md_theme_dark_tertiaryContainer = Color(0xFF004D65)
val md_theme_dark_onTertiaryContainer = Color(0xFFBEE9FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C19)
val md_theme_dark_onBackground = Color(0xFFE2E3DD)
val md_theme_dark_surface = Color(0xFF1A1C19)
val md_theme_dark_onSurface = Color(0xFFE2E3DD)
val md_theme_dark_surfaceVariant = Color(0xFF42493F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C8BC)
val md_theme_dark_outline = Color(0xFF8C9388)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C19)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DD)
val md_theme_dark_inversePrimary = Color(0xFF006E11)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF6ADF62)
val md_theme_dark_outlineVariant = Color(0xFF42493F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF008E19)